application: my-shop
version: 1
runtime: python27
threadsafe: false

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /(.*\.(gif|png|jpg))$
  static_files: dist/static/\1
  upload: dist/static/.*\.(gif|png|jpg)$

- url: /
  script: main.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest